pipeline:
  name: pipelineremote_defaultbranch_repoa
  identifier: pipelineremote_defaultbranch_repoa
  template:
    templateRef: pipelineTemplate_feature_a
    versionLabel: s
    gitBranch: main_test
    templateInputs:
      stages:
        - stage:
            identifier: stg1
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  services:
                    values: <+input>
  tags: {}
  projectIdentifier: Jira
  orgIdentifier: default
