pipeline:
  name: pipeline_1_repo1_default
  identifier: pipeline_1_repo1_default
  template:
    templateRef: remote_default_gitsync
    versionLabel: vb
    templateInputs:
      stages:
        - stage:
            identifier: stgTemplate
            template:
              templateInputs:
                type: Approval
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: step2
                          template:
                            templateInputs:
                              type: Email
                              spec:
                                to: <+input>
                                body: <+input>
        - stage:
            identifier: stg1
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: stepTemplate
                      template:
                        templateInputs:
                          type: Email
                          spec:
                            to: <+input>
                            body: <+input>
  tags: {}
  projectIdentifier: Jira
  orgIdentifier: default
