pipeline:
  name: pipeline1
  identifier: pipeline1
  projectIdentifier: defaultproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg1
        identifier: stg1
        template:
          templateRef: stageTemplate1
          versionLabel: v2
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: step9
                      type: JiraApproval
                      spec:
                        connectorRef: <+input>
