pipeline:
  name: pipelineremote_defaultbranch_repoa
  identifier: pipelineremote_defaultbranch_repoa
  template:
    templateRef: pipelineTemplate_feature_a
    versionLabel: s
    gitBranch: main_test
    templateInputs:
      stages:
        - stage:
            identifier: stg_diffrepo_diffbrnach
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: ShellScript_1
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
        - stage:
            identifier: fd
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: step_samerepo_diffbvranch
                      template:
                        templateInputs:
                          type: Email
                          spec:
                            to: <+input>
                            body: <+input>
  tags: {}
  projectIdentifier: Jira
  orgIdentifier: default
