pipeline:
  name: pipeline3
  identifier: pipeline3
  projectIdentifier: defaultproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg1_repoA_diffbranch
        identifier: stg1_repoA_diffbranch
        template:
          templateRef: stage1_repoA_defaultbranch
          versionLabel: v2
          gitBranch: main
          templateInputs:
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: ShellScript_1
                      type: ShellScript
                      spec:
                        source:
                          type: Inline
                          spec:
                            script: <+input>
    - stage:
        name: stg2_repoA_samebranch
        identifier: stg2_repoA_samebranch
        template:
          templateRef: stage2_repoA_featurebranch
          versionLabel: v3
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: custom1
                      type: CustomApproval
                      spec:
                        outputVariables:
                          - name: abc
                            type: String
                            value: <+input>
