pipeline:
  name: remotepipeline_main-test
  identifier: remotepipeline_maintest
  projectIdentifier: Jira
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg45
        identifier: stg45
        template:
          templateRef: stage_template_1
          versionLabel: v2
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
    - stage:
        name: stg3
        identifier: stg3
        template:
          templateRef: stage_template_1
          versionLabel: v2
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
