pipeline:
  name: remotepipeline_featurebranch
  identifier: remotepipeline_featurebranch
  template:
    templateRef: test2_repoA_featurebranch
    versionLabel: v8
    gitBranch: main_test
    templateInputs:
      stages:
        - stage:
            identifier: t1_repoA_feature_defaultbehaviour
            template:
              templateInputs:
                type: Approval
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: custom1
                          type: CustomApproval
                          spec:
                            outputVariables:
                              - name: abc
                                type: String
                                value: <+input>
        - stage:
            identifier: t2_repoB_default_defaultbehaviour
            template:
              templateInputs:
                type: Approval
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: harnessaproval
                          type: HarnessApproval
                          spec:
                            approvers:
                              userGroups: <+input>
        - stage:
            identifier: t4_repoA_default_staticbehaviour
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: ShellScript_1
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
  tags: {}
  projectIdentifier: defaultproject
  orgIdentifier: default
