pipeline:
  name: stepTemplateUsecase
  identifier: stepTemplateUsecase
  projectIdentifier: Jira
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: de
        identifier: de
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: <+input>
            serviceInputs: <+input>
          environment:
            environmentRef: <+input>
            deployToAll: false
            environmentInputs: <+input>
            serviceOverrideInputs: <+input>
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
              - step:
                  name: mainstep
                  identifier: mainstep
                  template:
                    templateRef: step_template_2
                    versionLabel: v6
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: stg2
        identifier: stg2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: steptemplatefromdifferentbranch
                  identifier: steptemplatefromdifferentbranch
                  template:
                    templateRef: account.AccountStepRemoteOct6
                    versionLabel: v1
              - step:
                  name: gfds
                  identifier: gfds
                  template:
                    templateRef: account.AccountStepRemoteOct6
                    versionLabel: v1
                    gitBranch: main
              - step:
                  name: gfd
                  identifier: gfd
                  template:
                    templateRef: account.AccountStepRemoteOct6
                    versionLabel: v1
                    gitBranch: a-main-patch
        tags: {}
    - stage:
        name: stg67890
        identifier: stg67890
        template:
          templateRef: stage_template_1
          versionLabel: v2
          gitBranch: main_test
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
    - parallel:
        - stage:
            name: stge_fifferenntbranch
            identifier: stge_fifferenntbranch
            template:
              templateRef: stage_template_1
              versionLabel: v2
              gitBranch: main_test
              templateInputs:
                type: Deployment
                spec:
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
        - stage:
            name: uhygtfrdeswdefrtgyh
            identifier: uhygtfrdeswdefrtgyh
            template:
              templateRef: stage_template_1
              versionLabel: v2
              gitBranch: main_test
              templateInputs:
                type: Deployment
                spec:
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
