pipeline:
  name: DefaultBranchPipeline_cypressTestUseCase
  identifier: DefaultBranchPipeline_cypressTestUseCase
  tags: {}
  projectIdentifier: Jira
  orgIdentifier: default
  stages:
    - stage:
        name: stg1
        identifier: stg1
        tags: {}
        template:
          templateRef: stagetestmain
          versionLabel: g7
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              services:
                values: <+input>
    - stage:
        name: stg2
        identifier: stg2
        tags: {}
        template:
          templateRef: ip_stageTemplate_featurebranch
          versionLabel: v1
          gitBranch: main_test
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
              execution:
                steps:
                  - step:
                      identifier: Wait_1
                      type: Wait
                      spec:
                        duration: <+input>
    - stage:
        name: stg3
        identifier: stg3
        tags: {}
        template:
          templateRef: org.OrgStage
          versionLabel: v1
          templateInputs:
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: Org_Step
                      template:
                        templateInputs:
                          type: Wait
                          spec:
                            duration: <+input>
                          when: <+input>
                          failureStrategies: <+input>
                          strategy: <+input>
